# Railway Configuration for Vigil ML Service
# Docs: https://docs.railway.com/guides/config-as-code

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python3 run_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

