# Railway Configuration for Vigil Intelligent Router
# Docs: https://docs.railway.com/guides/config-as-code

[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "./vigil-router"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

