name: Secret Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history for better scanning

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

      - name: Check for .env files
        run: |
          echo "Checking for accidentally committed .env files..."
          if git ls-files | grep -E "\.env$"; then
            echo "ERROR: .env files should not be committed!"
            exit 1
          else
            echo "✓ No .env files found in repository"
          fi

      - name: Check for API keys in code
        run: |
          echo "Scanning for potential API keys..."
          # Check for common API key patterns
          if grep -r -E "(api-key|api_key|apikey)=['\"]?[A-Za-z0-9]{20,}" --exclude-dir=.git --exclude-dir=venv --exclude="*.md" --exclude="*.example" .; then
            echo "WARNING: Potential API keys found in code"
            echo "Please review and move to .env files"
            exit 1
          else
            echo "✓ No obvious API keys found in code"
          fi
